"""initial schema

Revision ID: 2548b632b722
Revises: 
Create Date: 2026-08-07 21:42:05.578521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2548b632b722'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('old', sa.Text(), nullable=True),
    sa.Column('new', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=50), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kb_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('textbook_edition', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parse_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_version_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=50), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('q_type', sa.String(length=20), nullable=False),
    sa.Column('full_score', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('source_template_question_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['kb_version_id'], ['kb_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kb_version_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=100), nullable=False),
    sa.Column('cog_levels_expected', sa.JSON(), nullable=False),
    sa.Column('difficulty_prior', sa.Float(), nullable=False),
    sa.Column('mastery_floor', sa.Float(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kb_version_id'], ['kb_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_version_id', 'code', name='uq_kb_code')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('parse_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kp_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_kp_id', sa.Integer(), nullable=False),
    sa.Column('to_kp_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('audit_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['from_kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['to_kp_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name_or_alias', sa.String(length=100), nullable=False),
    sa.Column('external_code', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teaching_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('taught_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'kp_id', name='uq_progress')
    )
    op.create_table('attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('root_kp_id', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('prediction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['root_kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_template_id', 'student_id', name='uq_tpl_student')
    )
    op.create_table('intervention_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('q_type', sa.String(length=20), nullable=False),
    sa.Column('full_score', sa.Float(), nullable=False),
    sa.Column('cog_level', sa.String(length=20), nullable=False),
    sa.Column('difficulty_est', sa.Float(), nullable=False),
    sa.Column('n_options', sa.Integer(), nullable=True),
    sa.Column('sub_items_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_template_id', 'idx', name='uq_tpl_q')
    )
    op.create_table('parse_batch_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parse_job_id', sa.Integer(), nullable=False),
    sa.Column('exam_template_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('detected_name', sa.String(length=100), nullable=True),
    sa.Column('matched_student_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_template.id'], ),
    sa.ForeignKeyConstraint(['matched_student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['parse_job_id'], ['parse_job.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['exam_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pbi_exam', 'parse_batch_item', ['exam_template_id'], unique=False)
    op.create_index('ix_pbi_job', 'parse_batch_item', ['parse_job_id'], unique=False)
    op.create_table('plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('bank_question_id', sa.Integer(), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bank_question_id'], ['bank_question.id'], ),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['intervention_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_kp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_question_id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['template_question_id'], ['template_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_question_id', 'kp_id', name='uq_q_kp')
    )
    op.create_table('response_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_response_id', sa.Integer(), nullable=False),
    sa.Column('template_question_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('chosen_option', sa.String(length=10), nullable=True),
    sa.Column('sub_scores_json', sa.JSON(), nullable=True),
    sa.Column('cascade_flag', sa.Boolean(), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exam_response_id'], ['exam_response.id'], ),
    sa.ForeignKeyConstraint(['template_question_id'], ['template_question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_response_id', 'template_question_id', name='uq_resp_q')
    )
    op.create_table('evidence_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('kp_id', sa.Integer(), nullable=False),
    sa.Column('response_answer_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cog_level', sa.String(length=20), nullable=False),
    sa.Column('class_avg_rate', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('algo_version', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_point.id'], ),
    sa.ForeignKeyConstraint(['response_answer_id'], ['response_answer.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retest_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_item_id', sa.Integer(), nullable=False),
    sa.Column('mastery_before', sa.Float(), nullable=False),
    sa.Column('mastery_after', sa.Float(), nullable=False),
    sa.Column('improved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retest_outcome')
    op.drop_table('evidence_event')
    op.drop_table('response_answer')
    op.drop_table('question_kp')
    op.drop_table('plan_item')
    op.drop_index('ix_pbi_job', table_name='parse_batch_item')
    op.drop_index('ix_pbi_exam', table_name='parse_batch_item')
    op.drop_table('parse_batch_item')
    op.drop_table('template_question')
    op.drop_table('report')
    op.drop_table('intervention_plan')
    op.drop_table('exam_response')
    op.drop_table('attribution')
    op.drop_table('teaching_progress')
    op.drop_table('student')
    op.drop_table('kp_relation')
    op.drop_table('exam_template')
    op.drop_table('teacher')
    op.drop_table('knowledge_point')
    op.drop_table('class')
    op.drop_table('bank_question')
    op.drop_table('school')
    op.drop_table('parse_job')
    op.drop_table('kb_version')
    op.drop_table('correction_log')
    # ### end Alembic commands ###
